### ISSUE TITLE
Failed to receive LoRa packets with SF 12

### ISSUE THREAD

**Issue by IoTThinks** [SMotlaq/LoRa_third#10]
Hi all,
I have tested to send packet from Sandeep's Arduino LoRa (ESP32) to SMotlag's LoRa (STM32).
When SF = 7, STM32 can receive packets from ESP32.
However, when SF=12, then STM32 does not receive packets from ESP32.

Compare the set Spreading Factor function, I guess this library misses the part to set LDO (Low data optimization).
This library
https://github.com/SMotlaq/LoRa/blob/master/LoRa/LoRa.c#L184

Sandeep's library
https://github.com/sandeepmistry/arduino-LoRa/blob/master/src/LoRa.cpp#L573

RadioLib's library
https://github.com/jgromes/RadioLib/blob/master/src/modules/SX127x/SX1278.cpp#L188

Have you tested the receiving with SF12?
Thanks a lot.

**Comment by SMotlaq** [comment]
Thanks for bringing this issue to my attention. I apologize for the confusion caused by the missing Low Data Optimization (LDO) setting in my LoRa library. I understand that this feature is important for reliable data transmission when using a Spreading Factor (SF) of 12.

I've now added the necessary code to set the LDO in the LoRa library. You can find the updated code in the following commit:

https://github.com/SMotlaq/LoRa/commit/0bf5cb70da10118b0dd6729fc7ed5118bd6b9e5e

The changes include the addition of two new functions: ```LoRa_setLowDaraRateOptimization``` and ```LoRa_setAutoLDO```. These functions allow you to enable/disable LDO and set the LDO flag for your specific use case.

Unfortunately I couldn't test the updated library with SF12. Please check these new functions and tell me the result.

Thanks again for bringing this to my attention, and I apologize for any inconvenience caused. If you have any further questions or concerns, please don't hesitate to reach out 🌹

**Comment by IoTThinks** [comment]
I have attempted to creat a fix. But not successful yet.

Let me test your patch tomorrow morning.

**Comment by IoTThinks** [comment]
I tested just now.
The fix works for SF7-10 and SF12.
SF11 seems not working yet. Still show wrong data for SF11.

<img width="418" alt="image" src="https://github.com/SMotlaq/LoRa/assets/29994971/a2e6ee46-cff0-4fe0-9cea-76a0fbe3fc7e">

**Comment by SMotlaq** [comment]
Thanks. Would you mind sending your code please?

**Comment by IoTThinks** [comment]
My code is not working yet.

Let me debug and try to fix for sf11 based on your fix yesterday.

Hope to complete by this Friday.

Will update you and creat pull request if success.

**Comment by IoTThinks** [comment]
I think there is still missing code here and there comparing to RadioLib and ArduinoLoRa.
However, this is a dirty trick.
SF7-11 should not have LDO on. SF12 should have LDO on.
((1 << _LoRa->spredingFactor) / ((double)BW[_LoRa->bandWidth] will return 16.3... so it will larger than 16.

So Arduino-LoRa uses "long" so after debugging, I guess it would trim down to 16.
<img width="956" alt="image" src="https://github.com/SMotlaq/LoRa/assets/29994971/6cdc5575-0beb-489d-bdcb-705386062c83">

So my suggested fix is to change this line
https://github.com/SMotlaq/LoRa/blob/0bf5cb70da10118b0dd6729fc7ed5118bd6b9e5e/LoRa/LoRa.c#L180

To the below.
Note the (long) and =

`	LoRa_setLowDaraRateOptimization(_LoRa, (long)((1 << _LoRa->spredingFactor) / ((double)BW[_LoRa->bandWidth])) > 16.0);`

My STM32L0 with this fix is able to receive SF7-12 packets from Arduino-LoRa now.
<img width="483" alt="image" src="https://github.com/SMotlaq/LoRa/assets/29994971/88399a35-7957-4a06-94af-208601da295f">

**Comment by SMotlaq** [comment]
Hi again,

Thanks for your suggestion to fix the issue. I agree that changing the line to use `long` and `>` operator would fix the issue.

Would you be willing to make this change in your forked repository and send a pull request? This way, we can keep the changes in your repository and I can merge them into the main repository.

If you're not comfortable making the changes yourself, I can certainly do it myself. However, I'd like to give you the opportunity to make the changes and get credit for your contribution.

Let me know either way, and we can move forward with the fix.

Thanks again!

**Comment by IoTThinks** [comment]
Ok, let me create a pull request tomorrow.

**Comment by IoTThinks** [comment]
I created a Pull Request.
To close this issue.
Thanks a lot for your effort.
